### ISSUE TITLE
Test the plugin

### ISSUE THREAD

**Issue by kalbers** [omeka/plugin-TxtAnnotation#10]
It should be pretty self-explanatory. You can choose from the two services, and then see if you can add annotations.

**Comment by mebrett** [comment]
What is the expected behavior of the plugin?

**Comment by mebrett** [comment]
Using either service, I was able to add commentary, etc, to any text on any public page of the install, once I had created accounts with the specific services (hypotheosis and annotateIt). 

When viewing items with audio or video media files attached, I get the following message:  `Notice: Undefined index: linkToFile in /websites/omekadev/home/www/mebrett/Omeka/plugins/TxtAnnotation/TxtAnnotationPlugin.php on line 36` - see http://dev.omeka.org/mebrett/Omeka/items/show/1034 for an example.
